server:
  port: 8088
  servlet:
    context-path: /
spring:
  application:
    name: authorityManagement
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #swagger必要配置
    static-path-pattern: /file/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/authority_management?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB #单次文件的最大限制
      resolve-lazily: true
  messages:
    encoding: UTF-8
    ## 配置国际化绑定的文件 不绑定会乱码
    basename: i18n.internationalization
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
web:
  upload-path: D:/home/authorityManagement-fileFolder/
  modular:
    statistics: /statisticsTemporary
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: 123456
#useSSL: 'false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8'
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: -1
      logic-not-delete-value: 0
#mybatis:
#  mapper-locations: classpath:com/planet/module/authManage/mapper/xml/*.xml
# shiro-redis配置
#shiro-redis:
#  enabled: true
#  redis-manager:
#    host: 127.0.0.1:6379
#    password: 123456
logging:
  #level 日志等级 指定命名空间的日志输出
  level:
    com.planet: debug
  file:
    path: D:/home/authorityManagement-fileFolder/log/authorityManagement.log
  pattern:
    console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n'
    pattern:
      file: '%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n'














